Component - ZList - add new component
ZanichelliEditore/design-system pull request #132
Opened 2021-07-08 15:02 UTC by StefanoMarcolini97

# Component - ZList - add new component

----

### Motivation and Context
Move old ZList component to snowflakes and add new ZList component [link](https://zanichelli.atlassian.net/browse/CLAV-76)

### Priority

- [ ] 1 - Highest
- [x] 2 - High
- [ ] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Component (add a Component as approved dy Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract
[link](https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/bf581376-62a1-467a-b896-e1ac15d7a180/commits/latest/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/04495C7A-9C53-4F40-9815-DEC46DE06876?collectionId=bb622d00-ffb2-4fa9-b12c-6cb0646fb6bb&collectionLayerId=0e1b63e8-dab3-4453-bab3-5aa444da9555)

### Screenshots

### Note

----

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2021-07-09 14:54 UTC, DarioSacco commented
Lascio qui i commenti riguardo la validazione funzionale/grafica:
- non è implementata la _mutua esclusività_ dei due utilizzi del divider di cui si parla nella scheda
- il padding-left dell'icona nella versione `expandable` non dovrebbe esserci. o meglio: o si mette in tutte le varianti o si lascia tutta la gestione degli spazi esterni al container che ospita il componente.
- gli elementi espandibili non si possono aprire tramite tastiera (con `space` o `enter`). potrebbe essere comodo usare il [tag html `details`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) in combo col tag `summary` (facendo override degli stili di default del browser) che gestisce già la funzionalità di apertura/chiusura stile accordion.

### Header gruppi
- non rispetta le indicazioni tipografiche della scheda di design (la scheda dice che di default è: `—body-level-4 semibold SX —grey-700`)
- non rispetta le spaziature (padding top/bottom). il testo infatti è attaccato al divider
- neanche il divider rispetta le spaziature (la scheda dice che deve avere un `margin-bottom` di 8 px)

2021-07-09 14:55 UTC, DarioSacco commented
Lascio qui i commenti riguardo la validazione funzionale/grafica:
- non è implementata la _mutua esclusività_ dei due utilizzi del divider di cui si parla nella scheda
- il padding-left dell'icona nella versione `expandable` non dovrebbe esserci. o meglio: o si mette in tutte le varianti o si lascia tutta la gestione degli spazi esterni al container che ospita il componente.
- gli elementi espandibili non si possono aprire tramite tastiera (con `space` o `enter`). potrebbe essere comodo usare il [tag html `details`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) in combo col tag `summary` (facendo override degli stili di default del browser) che gestisce già la funzionalità di apertura/chiusura stile accordion.

### Header gruppi
- non rispetta le indicazioni tipografiche della scheda di design (la scheda dice che di default è: `—body-level-4 semibold SX —grey-700`)
- non rispetta le spaziature (padding top/bottom). il testo infatti è attaccato al divider
- neanche il divider rispetta le spaziature (la scheda dice che deve avere un `margin-bottom` di 8 px)

2021-07-09 14:59 UTC, DarioSacco commented
Lascio qui i commenti riguardo la validazione funzionale/grafica:
- non è implementata la _mutua esclusività_ dei due utilizzi del divider di cui si parla nella scheda
- il padding-left dell'icona nella versione `expandable` non dovrebbe esserci. o meglio: o si mette in tutte le varianti o si lascia tutta la gestione degli spazi esterni al container che ospita il componente.
- gli elementi espandibili non si possono aprire tramite tastiera (con `space` o `enter`). potrebbe essere comodo usare il [tag html `details`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) in combo col tag `summary` (facendo override degli stili di default del browser) che gestisce già la funzionalità di apertura/chiusura stile accordion.

### Header gruppi
- non rispetta le indicazioni tipografiche della scheda di design (la scheda dice che di default è: `—body-level-4 semibold SX —grey-700`)
- non rispetta le spaziature (padding top/bottom). il testo infatti è attaccato al divider
- neanche il divider rispetta le spaziature (la scheda dice che deve avere un `margin-bottom` di 8 px)

2021-07-09 14:59 UTC, DarioSacco commented
Lascio qui i commenti riguardo la validazione funzionale/grafica:
- non è implementata la _mutua esclusività_ dei due utilizzi del divider di cui si parla nella scheda
- il padding-left dell'icona nella versione `expandable` non dovrebbe esserci. o meglio: o si mette in tutte le varianti o si lascia tutta la gestione degli spazi esterni al container che ospita il componente.
- gli elementi espandibili non si possono aprire tramite tastiera (con `space` o `enter`). potrebbe essere comodo usare il [tag html `details`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) in combo col tag `summary` (facendo override degli stili di default del browser) che gestisce già la funzionalità di apertura/chiusura stile accordion.

### Header gruppi
- non rispetta le indicazioni tipografiche della scheda di design (la scheda dice che di default è: `—body-level-4 semibold SX —grey-700`)
- non rispetta le spaziature (padding top/bottom). il testo infatti è attaccato al divider
- neanche il divider rispetta le spaziature (la scheda dice che deve avere un `margin-bottom` di 8 px)

2021-07-12 08:38 UTC, DarioSacco requested changes

2021-07-12 08:38 UTC, DarioSacco commented on src/components/list/z-list/styles.css
> + * Horizontal
mi sa che intendevi vertical 🤔 anche se non vedo nessuna versione orizzontale nella scheda abstract, lo toglierei per evitare confusione

2021-07-12 08:38 UTC, DarioSacco commented on src/components/logo/z-logo/index.stories.mdx
> +{" "}
?

2021-07-12 08:38 UTC, DarioSacco commented on src/snowflakes/myz/list/z-myz-list/index.tsx
> +export class ZList {
non dovrebbe cambiare anche il nome della classe?

2021-07-21 08:49 UTC, DarioSacco requested changes

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-element/index.tsx
> +  _renderExpandedContent() {
solo per curiosità: come mai l'underscore? 🤔  che io sappia si usa come convenzione per i metodi privati in javascript ma qui siamo in typescript e la keyword `private` esiste

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-element/styles.css
> +  outline: none;
questo va messo anche a `:host` altrimenti il suo outline copre la shadow

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-element/styles.css
> +:host > .container {
questo selettore è definito 3 volte, vanno unite le regole

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-element/index.tsx
> +  @Prop() expandable?: boolean = false;
l'attributo expandable viene usato anche nel css, quindi qui ci va `{ reflect: true }`

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-group/index.tsx
> +        this.expandable ? "true" : "false"
andava bene anche `this.expandable.toString()` :)

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-group/index.tsx
> +            ["body-4-sb"]: true,
non servono le quadre

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-group/index.tsx
> +            <div class="z-divider-container">
come mai questo `div` container?

2021-07-21 08:49 UTC, DarioSacco commented on src/components/list/z-list-group/styles.css
> +  color: var(--text-grey-700);
la variabile `--text-grey-700` è legacy, quella nuova è `--gray700`

2021-07-21 08:55 UTC, DarioSacco requested changes

2021-07-21 08:55 UTC, DarioSacco commented on src/components/list/z-list-element/styles.css
> +  flex-direction: column;
qui ci va `justify-content: center` per allineare verticalmente il contenuto. attualmente si disallinea un po' per via della `min-height`

2021-07-21 08:56 UTC, DarioSacco commented
Soliti commenti di validazione grafica/funzionale:
- la lista senza header ha un padding top sbagliato che rimane dal container dell'header anche se è vuoto
- l'_inner content_ non ha distanziamento dall'element che lo mostra
- gli element con `expandable="false"` e  senza l'attributo `clickable` non dovrebbero avere il `cursor: pointer` e il colore di sfondo all'hover (forse è un problema solo su storybook. non viene rimosso l'attributo `expandable` quando settato a `false`)
- l'`header-title` ha un font-weight sbagliato, dovrebbe essere semibold

2021-07-21 13:45 UTC, StefanoMarcolini97 commented on src/components/list/z-list-group/index.tsx
> +            <div class="z-divider-container">
Per aggiungere il padding, ma ho visto che si può riuscire senza, lo rimuovo.

2021-07-23 10:02 UTC, DarioSacco approved these changes

2021-07-23 10:04 UTC, francescochiapella approved these changes

2021-07-23 10:18 UTC, merged