Feature - ZAppTopbar - adapt to new UI specifications
ZanichelliEditore/design-system pull request #197
Opened 2022-01-04 12:09 UTC by alessandrodolci

# Feature - ZAppTopbar - adapt to new UI specifications

### Motivation and Context
This set of changes was made to follow the rework of the component user interface.
For reference, see [ZTE-4389](https://zanichelli.atlassian.net/browse/ZTE-4389), [ZTE-4390](https://zanichelli.atlassian.net/browse/ZTE-4390), and the [Abstract specification](https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/98773628-20c4-44d3-8184-ea44e47e0c57/collections/150f6337-8425-4fe7-9875-3fddc362f857).

### Priority

- [ ] 1 - Highest
- [x] 2 - High
- [ ] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract

https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/98773628-20c4-44d3-8184-ea44e47e0c57/collections/150f6337-8425-4fe7-9875-3fddc362f857

2022-01-04 14:16 UTC, Abr89 commented on src/components/navigation/z-app-topbar/styles.css
> +#right-panel > :not(:last-child) {
A livello di CSS c'è una reale differenza tra #left-panel e #right-panel?

2022-01-04 15:18 UTC, alessandrodolci commented on src/components/navigation/z-app-topbar/styles.css
> +#right-panel > :not(:last-child) {
Giusta osservazione, posso provare a unificare usando una classe.

2022-01-04 16:45 UTC, Abr89 approved these changes

2022-01-10 10:20 UTC, DarioSacco requested changes

2022-01-10 10:20 UTC, DarioSacco commented on src/components/navigation/z-user-dropdown/styles.css
> +    padding-right: calc(var(--space-unit) * 3 + 2px);
da abstract mi sembra così

```suggestion
    padding-right: calc(var(--space-unit) * 2);
```

2022-01-10 10:20 UTC, DarioSacco commented on src/components/navigation/z-user-dropdown/styles.css
>    padding: calc(var(--space-unit) * 1.5 - 1px) 0;
questo padding è sbagliato. meglio chiedere ai designer perché su abstract vedo 18px, che come dicevo prima non è una misura molto usuale per il DS (non essendo a base 4)

2022-01-10 10:20 UTC, DarioSacco commented on src/components/navigation/z-user-dropdown/styles.css
>    margin: 0 calc(var(--space-unit) * 4) 0 0;
scrivo tutta la spiegazione qui: in mobile il box dell'`ul` non rispetta i padding del container, andando fuori dal box. la cosa si risolve mettendo `box-sizing: border-box;` all'`ul`. come conseguenza, il margin che era settato qui non serve più, perché i `li` finiscono già dove devono finire

```suggestion
  margin: 0;
```

2022-01-10 13:52 UTC, DavideDA commented on src/components/navigation/z-app-topbar/index.tsx
> +        <div id="content-container" class={`${this.contentmaxwidth ? "limited-width" : ""}`} style={this.contentmaxwidth ? { "--mw": `${this.contentmaxwidth}px` } : {}}>
Ti direi di no, perché la classe sull'Host fa sì che content-container si centri rendendo uguali i padding orizz di Host, mentre su content-container la medesima classe fa sì che venga applicato il css specifico

2022-01-10 15:28 UTC, DavideDA commented on src/components/navigation/z-user-dropdown/styles.css
>      padding: 0 calc(var(--space-unit) - 2px);
Abbiamo finito ora una review coi designer per controllare tutte le misure e, a parte alcune correzioni, ora sono giuste. Alcune però mantengono delle addizioni/sottrazioni che correggono le distanze. Per spiegazioni precise chiedi pure a loro.
In pratica le icone hanno padding orizzontali che rendono necessarie "sistemazioni" di qualche pixel, mentre nelle voci di dropdown l'altezza "tonda" è data dall'altezza totale degli elementi che compongono 1 riga, quindi i singoli componenti html che compongono la riga hanno misure non proprio multiple di --space-unit

2022-01-10 15:28 UTC, DavideDA commented on src/components/navigation/z-user-dropdown/styles.css
> +    padding-right: calc(var(--space-unit) * 3 + 2px);
Vedi il discorso qui sopra sulle spaziature

2022-01-10 15:29 UTC, DavideDA commented on src/components/navigation/z-user-dropdown/styles.css
>    padding: calc(var(--space-unit) * 1.5 - 1px) 0;
Vedi il discorso sopra sulle spaziature

2022-01-10 15:49 UTC, alessandrodolci commented on src/components/navigation/z-app-topbar/index.tsx
> +  @Prop() topbarcontent?: string | MenuItem[];
Dal momento che le specifiche lato UX stabiliscono che in quel contenitore debbano starci sempre degli ZLink, ci è sembrato ragionevole "bloccare" il più possibile l'implementazione da questo punto di vista, dando la possibilità di ridefinire solamente il contenuto dei link.
In tutta sincerità non ricordavo che ci fossimo accordati per mantenere lo slot, nel caso mi scuso. Mi dispiace che su questa cosa sembra non ci si riesca mai a trovare, probabilmente sono anche io che non ho ancora capito quale sia l'approccio da preferire per il DS.

2022-01-10 16:41 UTC, DarioSacco commented on src/components/navigation/z-app-topbar/index.tsx
> +  @Prop() topbarcontent?: string | MenuItem[];
nessun problema, va bene anche così. chiedevo perché anch'io non ho chiaro e non ero sicuro di ricordare bene

2022-01-13 10:38 UTC, DavideDA commented on src/components/navigation/z-app-topbar/index.tsx
> +  @Prop() contentmaxwidth?: number;
Non piace nemmeno a noi così, ma abbiamo trovato molti nomi così e pensavamo che fosse uno "standard" qui nel ds. Se per te va bene, ma direi di sì, li modifichiamo in camel case, che anche noi riteniamo più corretto. Però in giro c'è pieno di roba tutta minuscola 😢

2022-01-13 15:26 UTC, DarioSacco approved these changes

2022-01-17 10:22 UTC, merged