Feat/z toggle switch
ZanichelliEditore/design-system pull request #228
Opened 2022-04-21 15:52 UTC by PaoloFrancesco-Marino

# Title

----

### Motivation and Context

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract

### Screenshots

### Note

----

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2022-04-22 07:46 UTC, vpasquino commented on src/components/buttons/z-toggle-switch/index.tsx
> +  @Prop({ reflect: true }) labelposition?: boolean = false;
Una prop che si chiama `labelposition` non può essere un booleano.. O le dai valori left/right, oppure la gestisci diversamente, così non è proprio intuitiva come cosa.

2022-04-22 07:56 UTC, vpasquino commented on src/components/buttons/z-toggle-switch/index.tsx
> +    this.toggleClick.emit({
Per completezza aggiungerei l'id del componente, così se viene utilizzato un listener generico si può capire a che componente è legato l'evento.

2022-04-22 07:57 UTC, vpasquino commented on src/components/buttons/z-toggle-switch/styles.css
> +  cursor: pointer;
Il cursor pointer lo metterei sul container, visto che è tutto cliccabile.
Aggiungo anche che quando è disabled il cursor non deve essere pointer :sweat_smile:

2022-04-26 12:50 UTC, vpasquino commented on src/components/buttons/z-toggle-switch/index.tsx
> +          onKeyDown={(e: KeyboardEvent) => this.handleKeyboardEvent(e)}
Utilizzerei `onKeyDown` invece di `onKeyUp`, e sfrutterei il metodo `handleKeyboardSubmit` presente in utils, passandogli come callback la `this.handleClick`.
Aggiungerei il controllo sul disabled direttamente dentro la handleClick, così è valido per tutti e non dovrebbe creare problemi.

2022-04-27 13:24 UTC, vpasquino approved these changes

2022-04-28 12:35 UTC, saldomik requested changes

2022-04-28 12:35 UTC, saldomik commented on src/components/buttons/z-toggle-switch/index.tsx
> +      <label
L'utilizzo così della label non è conferme alle specifiche html, non si riesce a gestirlo diversamente?

Specifica: _Content model: Phrasing content, but with no descendant labelable elements unless it is the element's labeled control, and no descendant label elements._

2022-04-28 12:35 UTC, saldomik commented on src/components/buttons/z-toggle-switch/index.tsx
> +  @Prop({ reflect: true }) reverselabel?: boolean = false;
Questo reverse label mi sembra un po' criptico, perchè diamo per scontato che il default sia la label sulla sinistra credo...ma non è detto sia così. Una prop labelPosition left/right?

2022-04-28 12:35 UTC, saldomik commented on src/components/buttons/z-toggle-switch/styles.css
> +:host > label {
A parte il primo, siamo sicuri che :host serva sempre? Con shadow true non serve, puoi provare qui visto che c'è shadow false?

2022-05-04 10:35 UTC, DarioSacco commented on src/components/buttons/z-toggle-switch/index.tsx
> +  @Prop({ reflect: true }) labelposition?: boolean = false;
concordo

2022-05-04 14:01 UTC, DarioSacco requested changes

2022-05-06 14:01 UTC, DarioSacco requested changes

2022-05-06 14:01 UTC, DarioSacco commented on src/components/buttons/z-toggle-switch/styles.css
> +  box-shadow: var(--shadow-2);
sto riguardando la scheda su abstract e vedo che lì viene usata la `--shadow-1` (posto che neanche si vede e forse senza sarebbe uguale 😂)

2022-05-09 12:31 UTC, DarioSacco approved these changes

2022-05-17 08:19 UTC, saldomik approved these changes

2022-05-17 08:23 UTC, merged