Feat/z-carousel
ZanichelliEditore/design-system pull request #234
Opened 2022-05-05 14:29 UTC by StefanoMarcolini97

# Feature - Z-Carousel - add new component

----

### Add carousel component

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract
[link](https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/86a3c8c1-879e-45db-89c8-6b988e340714/commits/latest/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/73601D1F-4173-4B38-8AE3-4E0C60EFE70E?collectionId=0c1fd332-ecb9-4396-b47f-d839bea18fd6&collectionLayerId=3587b245-8d7d-42d9-ac8f-d39a67a2edd2)

### Screenshots

### Note

----

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2022-05-09 11:03 UTC, DarioSacco commented
nota per il futuro: non usare i codici delle issue di prodotto (tipo `CLAV-275`) nei nomi dei branch e commit di questo repo 😬

2022-05-09 11:03 UTC, DarioSacco requested changes

2022-05-10 12:43 UTC, StefanoMarcolini97 commented on package.json
> +  "version": "2.37.1-CLAV-275",
Refuso dopo una prova di integrazione su registro, sistemato

2022-05-10 12:44 UTC, StefanoMarcolini97 commented on src/components/z-carousel/index.tsx
> +      <Host>
Ok chiaro, lo rimuovo

2022-05-10 12:48 UTC, StefanoMarcolini97 commented on src/components/z-carousel/z-carousel-item/index.tsx
> +      <li class="carousel-item" style={{ paddingRight: `${this.gutter}px` }}>
In effetti le due cose sono equivalenti, avevamo creato lo z-carousel-item prendendo ad esempio lo z-list

2022-05-11 07:04 UTC, DarioSacco commented on src/components/z-carousel/index.stories.mdx
> +The size of the carousel children fits to the size of the children
non ho capito che intendi con questa frase 🤔

2022-05-11 07:04 UTC, DarioSacco commented on src/components/z-carousel/index.tsx
> +      <div>
come mai questo `div` e non direttamente `ul`?

2022-05-11 09:02 UTC, DarioSacco approved these changes

2022-05-11 09:15 UTC, merged