Refactor/z status tag add avatar tokens changed name
ZanichelliEditore/design-system pull request #244
Opened 2022-05-25 15:50 UTC by vonaxl

# Refactoring of z-status-tag, changed to z-tag

----

### Motivation and Context
https://zanichelli.atlassian.net/browse/MYZ-8458

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [x] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/8c5ba0dc-29c1-4b7f-b0bc-5e35b8022ed9/commits/latest/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/D039B0B1-87AB-48E4-BCC6-7D8DECE953AB?collectionId=ce224306-f8c2-4aa6-825b-d0d907f4708d&collectionLayerId=491caa2a-6a84-4f57-8a09-5bdaef9a75a4

### Screenshots

### Note

----

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2022-05-26 09:16 UTC, vpasquino commented on src/components/z-tag/index.tsx
> +  /** [optional] Color token for the icon and text */
:eyes: @PaoloFrancesco-Marino

2022-06-08 07:55 UTC, DarioSacco requested changes

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/index.stories.mdx
> +import { Meta, Canvas, Story, Preview, Props } from "@storybook/addon-docs";
```suggestion
import { Meta, Canvas, Story, ArgsTable } from "@storybook/addon-docs";
```
`Preview` e `Props` sono deprecate

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/index.stories.mdx
> +<Props of="z-tag" />
```suggestion
<ArgsTable of="z-tag" />
```

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/index.stories.mdx
> +    icon: { control: { type: "text" } },
non so se qui può essere utile ma si può dare la lista delle icone nel control, così:
```
icon: {
  control: { type: "select" },
  options: Object.keys(icons).sort(),
},
```
importando l'oggetto delle icone
`import { icons } from "../../icons/icons";`

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/index.stories.mdx
> +      iconTextToken: "--color-white",
anche per i token colore si può fare una `select` con la lista, se interessa c'è un esempio nelle storie dello `z-section-title` :)

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/index.tsx
> +        })}
stencil sa fare le stesse cose di `classNames` già builtin
```suggestion
        class={{
          "body-5-sb": true,
          expandable: this.expandable && this.icon,
        }}
```

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/index.tsx
> +
manca la documentazione. soprattutto qui si possono documentare gli slot (con `@slot`) e le variabili css (con `@cssprop`) così da averle nella `ArgsTable` della tab `Docs` delle stories.

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/styles.css
> +  --bgToken: var(--color-hover-primary);
per i nomi dei token metterei un prefisso "univoco", per evitare eventuali conflitti con altri componenti. tipo: `--z-tag-text-color` e `--z-tag-bg`

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/styles.css
> +  --z-icon-height: 15px;
io da abstract vedo 14px

```suggestion
  --z-icon-width: 14px;
  --z-icon-height: 14px;
```

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/styles.css
> +  padding: 4px;
```suggestion
  padding: calc(var(--space-unit) / 2);
```

2022-06-08 07:55 UTC, DarioSacco commented on src/components/z-tag/index.stories.mdx
> +# ZTag token
questo titolo è uguale a quello sopra, meglio essere più precisi (questo titolo si vede nella pagina `Docs` su storybook)

2022-06-08 14:49 UTC, DarioSacco commented on src/components/z-tag/styles.css
> +  transition: max-width 0.3s ease-out, max-height 0.3s all;
mi sa che questo `all` alla fine non è valido 🤔 da devtools vedo che dà valore invalido ma togliendolo torna a posto

2022-06-08 15:14 UTC, DarioSacco requested changes

2022-06-08 15:14 UTC, DarioSacco commented on src/components/z-tag/styles.css
> +  height: fit-content;
questa `height` fa override di quella definita sopra da 22px. penso che quello giusto sia il secondo ma vedo che, quando si espande, c'è un "saliscendi" fastidioso a causa della dimensione del testo diversa da quella iniziale.
infatti da abstract leggo che su una riga l'altezza non deve superare i 22px, mentre su storybook è quasi a 24

2022-06-09 07:28 UTC, DarioSacco approved these changes

2022-06-09 15:15 UTC, merged