Draft: Refactor - ZPopover, ZTooltip
ZanichelliEditore/design-system pull request #265
Opened 2022-07-19 09:56 UTC by nicolocarpignoli

# Refactor - Z-Popover, Z-Tooltip

----

### Motivation and Context

Lo Z-tooltip al momento è una versione "estesa" ma non completa dello Z-popover. Si è vista la necessità di riusare la logica di un po' di entrambi i componenti in altri componenti (es. z-info-reveal-panel). E in generale, è bene concentrare in un solo componente la logica in comune, in questo caso quella di un elemento "flottante", posizionabile in base all'esigenza del contesto, con una serie di configurazioni possibile (la presenza della freccetta, il posizionamento al centro o meno, ombre e colori ecc.).

Per questo **è stato eliminato lo z-tooltip**, e migliorato e **reso più configurabile lo z-popover**: ora lo z-tooltip altro non è che lo z-popover con certe configurazioni ("center" sempre a true, ad esempio).

Di conseguenza sono stati adattati i componenti che usavano sia lo z-popover che lo z-tooltip.

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [x] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract

### Screenshots

### Note

----

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2022-07-19 13:13 UTC, DarioSacco requested changes

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.tsx
> +  @State() currentPosition?: PopoverPosition;
non ho capito bene a che serve questo state 🤔 visto che `position` è mutable, forse basta usare quella. se puoi prova

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.tsx
> +    console.log("sparo open", this.open);
🔫

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.stories.mdx
> +    position: PopoverPosition.right_bottom,
non sono in uppercase le chiavi dell'enum?

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.stories.mdx
> +    position: PopoverPosition.top,
anche qui

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.stories.mdx
> +import { Meta, Story, Preview, Props, ArgsTable } from "@storybook/addon-docs";
```suggestion
import { Meta, Story, Canvas, ArgsTable } from "@storybook/addon-docs";
```

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.stories.mdx
> +<Preview>
```suggestion
<Canvas>
```

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.stories.mdx
> +<Preview>
```suggestion
<Canvas>
```

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.stories.mdx
> +</Preview>
```suggestion
</Canvas>
```

2022-07-19 13:13 UTC, DarioSacco commented on src/components/z-popover/index.stories.mdx
> +<Props of="z-popover" />
```suggestion
<ArgsTable of="z-popover" />
```

2022-08-04 14:08 UTC, saldomik approved these changes

2022-08-05 08:13 UTC, merged