Feat - ZRangePicker
ZanichelliEditore/design-system pull request #267
Opened 2022-07-20 15:03 UTC by StefanoMarcolini97

# Feat - ZRangePicker

----

### Motivation and Context
Add new component

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract
[link](https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/b7f879d6-68dd-4ee1-b1f1-dafb9b2ca90b/commits/f7f41d422c98e420727392f86d826f41f7eb42d8/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/2426192B-D6F4-4FEE-AAA1-BDA80F4C9221?collectionId=2be28a4c-775b-4085-ac22-1485ada0fff5&collectionLayerId=40ce1b6e-8dbd-4a85-ad68-d72cc96313e8&mode=design&sha=latest)

### Screenshots

### Note

----

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2022-07-21 13:40 UTC, DarioSacco requested changes

2022-07-21 15:21 UTC, DarioSacco requested changes

2022-07-21 15:21 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.tsx
> +  AddClassToInput() {
come convenzione mettiamo sempre il nome delle funzioni in camelCase
```suggestion
  addClassToInput() {
```

2022-07-28 13:58 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.tsx
> +            onStopTyping={(value) => {
questa funzione la definirei fuori, così da rendere più leggibile l'html

2022-07-28 14:01 UTC, DarioSacco requested changes

2022-07-28 14:01 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.stories.mdx
> +This component has a callback function `dateSelect` that returns the selected date.
```suggestion
This component emits an event called `dateSelect` with the value of the selected date.
```

2022-08-01 14:42 UTC, StefanoMarcolini97 commented on src/components/date-picker/styles.css
> +z-range-picker > div > * {
Il problema si risolve rimpiazzando questa regola con

```
.range-picker-container > div {
  cursor: pointer !important;
}
```

2022-08-01 15:01 UTC, StefanoMarcolini97 commented on src/components/date-picker/z-range-picker/index.tsx
> +    this.hasChildren && customToggle.setAttribute("data-toggle", "data-toggle");
Sì è un refuso, rimuovo

2022-08-01 15:01 UTC, StefanoMarcolini97 commented on src/components/date-picker/z-range-picker/index.tsx
> +    }
Rimuovo, verrà gestito nella storia sull'accessibilità

2022-08-01 15:15 UTC, StefanoMarcolini97 commented on src/components/date-picker/z-range-picker/index.tsx
> +                      ` ${text} - ${this.getDate(
Sì, correggo

2022-08-01 15:20 UTC, StefanoMarcolini97 commented on src/components/date-picker/z-range-picker/index.tsx
> +    if (length > currentInputState.index) {
Sì, funzionava ugualmente anche prima ma mettendo length > 0 è più corretto

2022-08-01 16:04 UTC, DarioSacco requested changes

2022-08-01 16:04 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.tsx
> +    /** If range is already set, clicking another date it will update it */
questi non c'era bisogno di cambiarli anche qui, bastava solo sopra alla definizione delle funzioni. comunque non è un problema, fanno il loro lavoro anche così

2022-08-01 16:04 UTC, DarioSacco commented on src/components/date-picker/styles.css
>  }
mi sa che queste non servono più, il `left: 0` al `.flatpickr-calendar` viene già dato a riga 56 (infatti nei devtools vedo la regola due volte)

2022-08-01 23:17 UTC, StefanoMarcolini97 commented on src/components/date-picker/z-range-picker/index.tsx
> +        ?.children[0];
Ok, utilizzando la prop htmlid riesco a recuperare gli input specifici inclusi nei due z-input.

2022-08-02 07:55 UTC, DarioSacco commented on src/components/date-picker/styles.css
> +  box-shadow: 0 2px 4px 0 rgba(66, 69, 72, 0.4);
per questa shadow c'è il token
```suggestion
  box-shadow: var(--shadow-2);
```

2022-08-02 09:14 UTC, DarioSacco requested changes

2022-08-02 09:14 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.tsx
> +      appendTo: this.element.children[0].children[0].children[0] as HTMLElement,
sistemerei questi `appendTo`, magari usando `this.element.querySelector(`.${this.rangePickerId}-container`)` e con `-2` nell'altro

2022-08-02 09:14 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.tsx
> +    }
modificando come di seguito si potrebbe togliere il metodo `addClassToInput`
```suggestion
    const focusedZInput = document.activeElement.closest('z-input');
    if (!focusedZInput) {
      return;
    }

    if (focusedZInput?.classList.contains(RangePickerActiveInput.startInput)) {
      this.activeInput = RangePickerActiveInput.startInput;
    } else if (focusedZInput.classList.contains(RangePickerActiveInput.endInput)) {
      this.activeInput = RangePickerActiveInput.endInput;
    }
```

2022-08-02 09:14 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.tsx
> +
qui andrebbe aggiunta la jsdoc, documentando la variabile css `--toggle-height` (anche se non ho capito a che serve). poi le css vars dei componenti è meglio prefissarle con il nome del componente, tipo `--z-range-picker--toggle-height` per evitare conflitti di nome, non si sa mai

```suggestion

/**
 * Range picker component.
 * 
 * @cssprop --toggle-height - descrizione della variabile
 */
```

2022-08-02 14:07 UTC, StefanoMarcolini97 commented on src/components/date-picker/z-range-picker/index.stories.mdx
> +      </script>
È un modo per mostrare che viene restituito il valore del range selezionato, lo sostituisco con un box a lato anziché un console.log

2022-08-04 08:11 UTC, DarioSacco requested changes

2022-08-04 08:11 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.stories.mdx
> +    height="180px"
non penso funzioni questo attributo

2022-08-04 08:11 UTC, DarioSacco commented on src/components/date-picker/z-range-picker/index.stories.mdx
> +          style="display:flex; flex-direction: column; margin-left: 100px; border:1px solid black; width:400px; margin-top:40px; height:80px"
visto che c'è tanto stile inline, sarebbe meglio fare un file css a parte `index.stories.css` e importarlo qui

2022-08-04 14:21 UTC, DarioSacco approved these changes

2022-08-05 13:47 UTC, merged