Feature - ZBreadcrumb - add mobile version of component
ZanichelliEditore/design-system pull request #340
Opened 2023-03-09 14:42 UTC by StefanoMarcolini97

# Feature - ZBreadcrumb - add mobile version of component

## 

### Motivation and Context
Add the mobile version of Breadcrumb component

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract
[Figma](https://www.figma.com/file/w51ZwDwLNEt0yamar2sRRQ/Nuovi-Componenti-e-Pattern?node-id=616-2498)

### Screenshots

### Note

## 

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2023-03-10 14:23 UTC, saldomik requested changes

2023-03-10 14:23 UTC, saldomik commented on src/components/z-breadcrumb/index.tsx
> +  handleResize(): void {
Fatto così sicuramente funziona ma non sono sicuro sia il modo migliore di farlo. Magari pensiamo ad un modo differente e rivediamolo anche nelle storie successive.

2023-03-10 15:56 UTC, StefanoMarcolini97 commented on src/index.html
> +    <z-breadcrumb
Credo sia perché si vedono solamente con risoluzione mobile

2023-03-10 15:58 UTC, StefanoMarcolini97 commented on src/components/z-breadcrumb/index.tsx
> +  handleResize(): void {
Ok, avevo preso spunto dal componente z-table dove veniva fatta una gestione analoga

2023-03-15 13:59 UTC, StefanoMarcolini97 commented on src/components/z-breadcrumb/index.tsx
> +    return (
Come struttura dei dati viene consigliato di utilizzare liste ordinate ([link](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb#html_1)

Secondo me avrebbe senso wrappare il tutto all'interno del tag <nav></nav> visto che serve proprio per la navigazione ed è utile per alcuni controlli dello screen reader [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav?retiredLocale=it)

2023-03-16 08:00 UTC, saldomik approved these changes

2023-03-16 10:46 UTC, merged