Feature/z book card
ZanichelliEditore/design-system pull request #372
Opened 2023-07-07 10:27 UTC by vpasquino

# Feature - ZBookCard

## Priority

- [ ] 1 - Highest
- [X] 2 - High
- [ ] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] Feature (non-breaking change which adds functionality)
- [ ] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

## Design
https://www.figma.com/file/w51ZwDwLNEt0yamar2sRRQ/branch/34yBlDidf992KDto5Zef95/Nuovi-Componenti-e-Pattern?node-id=2750%3A8875

2023-07-17 08:12 UTC, DarioSacco requested changes

2023-07-17 13:10 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    if (this.moveFocusToResources) {
Sì il senso era proprio quello. Allora faccio due prove e provo a seguire questa strada, grazie.

2023-07-17 13:14 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    );
Se fosse passato meno tempo da quando ho scritto sto codice forse me lo ricorderei meglio :laughing: 
Diciamo che in questo modo mi sembra che lasciamo molto meno "libertà" al prodotto, lo stile è quello ed è imposto, con anche tutta la gestione dell'ellipsis. Non so se aggiungendo uno slot andiamo a complicare la cosa.

2023-07-17 13:14 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    return this.authors ? (
Tu hai molto ragione :woman_facepalming:

2023-07-17 13:15 UTC, DarioSacco requested changes

2023-07-17 13:16 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +  private renderShowResources(): null | JSX.Element {
Azz, temo che il null sia rimasto da una versione precedente. Rimuovo e sistemo anche le tipizzazioni.

2023-07-17 13:23 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +        aria-haspopup="menu"
Giusto il discorso su `aria-haspopup`, forse è un po' eccessivo :sweat_smile: 
Il resto però siamo sicuri che sia necessario? Io penso che l'`aria-expanded` e `aria-controls` siano già sufficienti a comunicare alle tecnologie assistive tutto quello che devono sapere. Magari sbagio eh, c'è sempre un grosso alone di mistero attorno a queste cose!

2023-07-17 13:34 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  height: auto;
Sei sicuro che sia bordeless? Questa mi pare la versione compatta coi bordi. Se così fosse, si tratta di un bordo trasparente (per evitare bordi accavallatti quando in realtà il bordo ce l'ha la card). Ricordo che era stata fatta questa scelta per fare meno casino coi calcoli, non mi sembrava orrenda :see_no_evil: 
Quella boderless invece non dovrebbe fare questo effetto, il bordo bianco è sempre a destra o in alto (scelta opinabile, ma quella è stata fatta..)

2023-07-17 13:36 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  margin-left: calc(var(--space-unit) * -2);
Perché l'ho copiato da un generatore di ribbon? :rofl: :see_no_evil:

2023-07-17 13:43 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  height: auto;
giuro, è proprio quella borderless 😂 da figma, riguardando adesso, vedo che ci sarebbe l'ombra sotto l'immagine tra l'altro.

per la questione dei calcoli, non dovrebbe succedere niente direi. la dimensione ce l'ha sempre il wrapper quindi l'immagine può anche riempire lo spazio che ha senza problemi. se è opinabile, opino 🤣

2023-07-17 13:45 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  line-height: initial;
Non me n'ero mica accorta, madonna che occhio di falco!

2023-07-17 13:47 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  border-left: 14px solid transparent;
Sono d'accordo con te, se va bene prendere questa iniziativa procedo!

2023-07-17 13:47 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  border-radius: 0 var(--border-radius) var(--border-radius) 0;
che non so leggere più 🤔 sorry ahah

2023-07-17 13:48 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +}
I tag incombrando sempre e solo una riga, quindi questo problema non si pone perché va tutto in overflow hidden

2023-07-17 13:51 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  align-items: top;
Il problema è che su mobile il titolo può andare su due righe e in quel caso fa un po' schifo l'align center. Come la gestiresti tu?
(comunque non so se hai visto dentro pages/book-cards.html, ci sono un mare di esempi già impostati che coprono più o meno tutte le casistiche :) )

2023-07-17 13:52 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  width: calc(var(--z-book-card-compact-width) - 4px);
Ci riprovo allora, in fase di sviluppo avevo avuto una serie di problemi, ma magari mi sono incasinata da sola.

2023-07-17 13:55 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  background: var(--color-white);
E' voluto in realtà. La scelta che è stata fatta nel rendere le cover visibili sempre al 100% senza tagliarle, e posizionandole in basso a sinistra, è dovuta anche al fatto che gran parte delle copertine Zanichelli in alto son bianche, e quindi appoggiarle sul fondo non crea un grave distacco visivo. Per questo motivo ho scelto di mettere sempre il contenitore bianco, anche quando il tema è scuro.

2023-07-17 13:59 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  border-color: var(--color-surface03);
Hai ragione, sistemo i bordi.

Esatto, è una delle cose definite in corso d'opera e non riportate sul figma. Ti mostro un caso concreto per rendere l'idea
![immagine](https://github.com/ZanichelliEditore/design-system/assets/67588501/6ff18cdf-4a0f-4c91-8045-91e77dc4cc6c)
Immagina questa card bordeless con la copertina senza il bordo. La copertina non è larga come tutta la card, e quindi sembra spostata a sinistra e buttata un po' lì nel mezzo. Col bordino, per quanto sia, riusciamo a definire una sorta di limite dell'immagine.

2023-07-17 14:00 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +    min-width: 265px;
Eh ti piacerebbe.. Loro li vogliono gli spazi vuoti.. La cover non si taglia e non si sforma..
Sistemo la larghezza in maniera coerente comunque.

2023-07-17 14:07 UTC, DarioSacco commented on src/components/z-book-card/index.tsx
> +        aria-haspopup="menu"
si vero sempre tutto fumoso... l'aria-hidden in effetti non serve, il labelledby forse non è fondamentale ma sapere cosa si è appena tabbato non fa male

2023-07-17 14:23 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    if (this.moveFocusToResources) {
Ho provato la tua soluzione ma la navigazione non fa quello che deve. Tu avevi provato?

2023-07-17 14:33 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    this.handleResources();
Mmh però questo mi serve per andare a contare le risorse slottato, e non dipende né dalla modifica di variant né da quella di isMobile, ma dal fatto che venga aggiunto qualcosa di slottato.

2023-07-17 14:41 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  border-color: var(--color-surface03);
Non la vogliono tagliare in nessuna direzione, si deve vedere tutta e con la razio giusta.
![immagine](https://github.com/ZanichelliEditore/design-system/assets/67588501/e30796cf-6231-4ee8-a221-252ec66ba3f2)

2023-07-17 14:50 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +}
in effetti hai ragione... se ti va puoi fare comunque la modifica che mi sembra più safe, sennò lascia pure perdere

2023-07-17 14:51 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  border-left: 14px solid transparent;
vai vai, mi assumo la responsabilità in caso di lamentele 🤣

2023-07-17 14:53 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  width: calc(var(--z-book-card-compact-width) - 4px);
se tornano fammi sapere!

2023-07-17 15:24 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  word-wrap: nowrap;
mi sa che `word-wrap` è una property non standard e quella che suggeriscono è `overflow-wrap` ma soprattutto non accetta `nowrap` tra i valori. non basta solo `white-space` come negli altri casi?

2023-07-17 15:39 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +:host div.cover {
Intendi che è come non scriverlo, giusto? Non va a fare danni?

2023-07-17 15:43 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  align-items: top;
temevo questa risposta sulle due righe 😞 forse ce l'ho: dare all'element dentro il `div.title`
```css
display: flex;
align-items: center;
height: 100%;
```

> ⚠️ va in conflitto col commento fatto prima che diceva di togliere il wrapper aggiuntivo quando viene passata la prop `operaTitleTag`

poi mi sa che conviene spostare gli stili del testo dal container al figlio, oppure replicarli tutti con `inherit` perché quel `unset: all` se li sta pappando 😢

2023-07-17 15:47 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +  height: auto;
Aah l'ombra cazzo, così posso togliere anche il bordino di merda!

2023-07-17 15:52 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  background: var(--color-white);
azz e io che pensavo fosse solo una svista! mi hai convinto anche qui 😶

2023-07-17 16:31 UTC, DarioSacco commented on src/components/z-book-card/index.tsx
> +    if (this.moveFocusToResources) {
si si. la mia situazione era: arrivi col tab al bottone per aprire, premi invio/space e si apre, tabbi di nuovo e davighi le risorse fino ad arrivare al bottone di chiusura, premi invio/enter e si chiude e al tab successivo ricomincia il loop.

tu come lo immaginavi il giro?

2023-07-17 16:36 UTC, DarioSacco commented on src/components/z-book-card/index.tsx
> +    this.handleResources();
aaah ok! allora forse basterebbe farlo in un `onSlotchange` dello slot resources

2023-07-17 16:38 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +:host div.cover {
si esatto è come non scriverlo

2023-07-17 16:40 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  height: auto;
🤣

2023-07-18 08:05 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    this.handleResources();
Aah benissimo, non lo conoscevo, funge! :D

2023-07-18 08:11 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    if (this.moveFocusToResources) {
Esattamente così, però non mi funziona se non lo forzo, se tabbo dopo il toggle delle risorse mi esce dalla card.

2023-07-18 09:28 UTC, DarioSacco requested changes

2023-07-18 09:28 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +:host > article.expanded z-link.show-resources {
ma non ci andrebbe il border-top quando è open? dalla scheda non capisco se quei bordi vengono tutti messi da prodotto oppure no

2023-07-18 09:32 UTC, DarioSacco requested changes

2023-07-18 09:32 UTC, DarioSacco commented on src/components/z-book-card/styles.css
> +  padding-top: var(--space-unit);
non dovrebbe essere 12 quando open?

2023-07-18 10:40 UTC, vpasquino commented on src/components/z-book-card/styles.css
> +    width: initial;
Temo sia solo un problema di storybook, comunque ok, ho provato e non cambia nulla

2023-07-18 11:06 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +    );
Lasciato per questione di allineamento

2023-07-18 13:53 UTC, DarioSacco requested changes

2023-07-20 12:14 UTC, DarioSacco commented
nella scheda di design dice che la variante search può avere il titolo su due righe viene troncato alla prima

<img width="344" alt="image" src="https://github.com/ZanichelliEditore/design-system/assets/15926182/047330f7-bcc6-4318-b78b-ab676cc6fa59">

2023-07-20 12:40 UTC, DarioSacco approved these changes

2023-07-20 13:14 UTC, merged