Feat/z book card/ribbon icon and cta
ZanichelliEditore/design-system pull request #402
Opened 2023-12-19 10:34 UTC by AlessandraMartera

# Feat - z book card - add ribbon icon and cta

## Motivation and Context
The new `ribbonIcon` prop allows the user to add an icon on the left side of ribbon text. 
When the `ribbonInteractive` is set to true, the component emits an `ribbonClick` event on click.

## Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [ ] 3 - Medium
- [x] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Component (add a Component as approved by Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

## Design

### Screenshots

### Note

2023-12-19 17:02 UTC, vpasquino commented on src/components/z-book-card/index.tsx
> +          <div
Il div non va bene: non è accessibile, non è tabbabile/focusabile, e non è gestito il click da tastiera.
La cosa migliore da fare sarebbe creare un button quando è interattivo (gestendone lo stile), e un div nelle altre situazioni.

2023-12-21 10:38 UTC, vpasquino commented on src/components/z-book-card/index.stories.mdx
> +    args={{ribbonIcon: "info", ribbonInteractive: true}}
Questa riga che è stata aggiunta non dovrebbe servire. Questa storia prende tutti gli args di default (come impostati alle linee 15-16), e mi sta bene che di default non ci sia l'icona né il ribbon interattivo. Poi l'utente è in grado di modificarli a suo piacere da interfaccia.

2023-12-21 10:38 UTC, vpasquino commented on src/components/z-book-card/index.stories.mdx
> +        ribbonIcon
Questa riga è un errore?

2023-12-21 10:39 UTC, vpasquino commented on src/components/z-book-card/index.stories.mdx
> +          ribbonIcon
Questo immagino sia un copiaincolla errato?

2023-12-21 11:15 UTC, AliGamb requested changes
Anche per me le stesse segnalazioni di Vale :), per il resto mi sembra a posto.

2023-12-21 14:37 UTC, vpasquino approved these changes

2023-12-21 16:18 UTC, AliGamb approved these changes

2024-01-04 08:33 UTC, merged