Chore - z-card - z-card refactoring
ZanichelliEditore/design-system pull request #61
Opened 2020-10-15 13:57 UTC by vpasquino

# Chore - z-card - z-card refactoring

----

### Motivation and Context

ZCard component restyle. 

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Component (add a Component as approved dy Design System)
- [ ] Docs (add documentation)
- [x] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract and Screenshots

https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/435673a7-8bdd-460b-a163-989e47deb4c0/collections/bc2a54a0-201f-4935-be84-7ee07bd027d3

2020-10-16 08:51 UTC, saldomik commented on src/components/card/z-card-footer/index.tsx
> +
Perhaps we can remove ellipsis on ISBN here, given that it is always visible now.

2020-10-16 10:13 UTC, saldomik approved these changes

2021-02-16 14:23 UTC, edoardocavazza requested changes

2021-02-16 14:23 UTC, edoardocavazza commented on src/components/card/z-card-footer/index.tsx
> +    this.footer.ontransitionend = event => {
Why programmatically adding the event listener instead of using the `@Listen` decorator of Stencil?

2021-02-16 14:23 UTC, edoardocavazza commented on src/components/card/z-card-footer/index.tsx
> +                  <b>{this.isbn}</b> (ed. cartacea)
Using the `<b>` tag prevents us from controlling the weight of the font with a design token. Better to use a span and the CSS `font-weight` property.

2021-02-16 14:27 UTC, edoardocavazza commented on src/components/card/z-card-footer/index.tsx
> +    this.footer.ontransitionend = event => {
Otherwise, instead of using the ref I think it would be better to inline the listener in the template.

2021-02-16 16:16 UTC, edoardocavazza approved these changes

2021-02-16 16:16 UTC, merged