Feature/z menu
ZanichelliEditore/design-system pull request #95
Opened 2021-04-28 14:30 UTC by DarioSacco

# ZMenu
feature - z-menu - togglable menu with an optional list of items
----

### Motivation and Context
Jira issue: https://zanichelli.atlassian.net/browse/DS-17
DS Menu component

### Priority

- [ ] 1 - Highest
- [ ] 2 - High
- [x] 3 - Medium
- [ ] 4 - Low
- [ ] 5 - Lowest
- [ ] 6 - Not a Priority

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Component (add a Component as approved dy Design System)
- [ ] Docs (add documentation)
- [ ] Chore (changes that adds small enhancement)
- [ ] Breaking (fix or feature that would cause existing functionality to not work as expected)

### Abstract
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/d77c80e0-38f3-4d9b-b0e3-28bf62f6e22e/commits/latest/files/7e5534c1-96e2-44c2-98f8-965c34ee8835/layers/37ABE5FE-EF8A-49CB-8484-595DDB8F5318?collectionId=1c1e3cd5-6ebf-4f65-a86d-bbce0db6d285&collectionLayerId=b786da9c-2ae9-406f-84e6-4975f77eac0a&mode=build&selected=root-7F33C35E-4F87-4295-9D7B-2E3B93180722

### Screenshots
<img width="492" alt="Schermata 2021-04-28 alle 16 29 30" src="https://user-images.githubusercontent.com/15926182/116421210-ec402e80-a83e-11eb-97d0-99aacb0d48c4.png">

### Note
ZMenu will be part of the ZAppHeader component, with all its layout variants. This PR also introduces the `z-menu-section` component to better handle sub-menus.

----

## Component and Fix approval flow to Master branch

A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team representative.

2021-05-06 14:16 UTC, a-sartori-wt approved these changes

2021-05-06 16:37 UTC, edoardocavazza requested changes

2021-05-06 16:37 UTC, edoardocavazza commented on src/components/navigation/z-menu-section/index.tsx
> +    this.toggle();
I would prefer to set the open state to false instead of using the toggle method.

2021-05-06 16:37 UTC, edoardocavazza commented on src/components/navigation/z-menu-section/styles.css
> +:host .label:hover {
we do not need the :host prefix for the third rule

2021-05-06 16:37 UTC, edoardocavazza commented on src/components/navigation/z-menu-section/styles.css
> +.items > ::slotted([slot='item']:focus-visible) {
this should be an unique selector `.items > ::slotted([slot='item']:focus:focus-visible)`

2021-05-07 06:57 UTC, edoardocavazza approved these changes

2021-05-07 07:11 UTC, merged